# Generated by Django 4.1.3 on 2022-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_contact_date_alter_contact_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя лида при контакте')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('contact_tstamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('edited_tstamp', models.DateTimeField(auto_now=True, verbose_name='Последние исправления')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, verbose_name='Дата рождения контакта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя контакта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия контакта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='patronym_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество контакта'),
        ),
    ]
