# Generated by Django 4.1.3 on 2022-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_lead_contact_date_of_birth_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_alter',
            field=models.CharField(default=None, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(blank=True, max_length=200, verbose_name='Объявление'),
        ),
    ]
