# Generated by Django 4.1.3 on 2022-12-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_listing_id_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
