# Generated by Django 4.1.3 on 2022-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
