# Generated by Django 4.1.3 on 2022-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_last_name_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
    ]
