# Generated by Django 4.1.3 on 2022-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_remove_contact_user_id_alter_contact_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing',
            field=models.CharField(blank=True, max_length=200, verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
