# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_listing_contact_listing_id_contact_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_alter',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
