# Generated by Django 4.1.3 on 2022-11-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_sqft_listing_sq_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 10, 27, 7, 892015, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_meters',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Площадь в кв.метрах'),
        ),
    ]
