# Generated by Django 4.1.3 on 2022-12-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 15, 41, 6, 471101, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
