# Generated by Django 4.1.3 on 2022-12-07 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 7, 45, 18, 427107, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
