# Generated by Django 4.1.3 on 2022-11-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_alter_realtor_description_alter_realtor_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 30, 10, 27, 7, 891016, tzinfo=datetime.timezone.utc), verbose_name='Дата найма'),
        ),
    ]
