# Generated by Django 4.1.3 on 2022-11-30 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Работает в настоящее время?'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 30, 11, 25, 58, 713017, tzinfo=datetime.timezone.utc), verbose_name='Дата найма'),
        ),
    ]
