# Generated by Django 4.1.3 on 2022-12-06 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 6, 16, 3, 41, 761823, tzinfo=datetime.timezone.utc), verbose_name='Дата найма'),
        ),
    ]
