# Generated by Django 4.1.3 on 2022-12-07 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0012_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 7, 7, 45, 18, 426069, tzinfo=datetime.timezone.utc), verbose_name='Дата найма'),
        ),
    ]
