# Generated by Django 4.1.3 on 2022-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0013_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата найма'),
        ),
    ]
