# Generated by Django 4.1.3 on 2022-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_holding_member',
            field=models.BooleanField(default=True),
        ),
    ]
