# Generated by Django 4.1.3 on 2022-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer_is_holding_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='is_holding_member',
            field=models.BooleanField(default=True, verbose_name='Входит в холдинг ВКБ?'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Работает в настоящий момент?'),
        ),
    ]
