# Generated by Django 4.1.3 on 2022-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developer_web_site_alter_developer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
    ]
