# Generated by Django 4.1.3 on 2022-12-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_listing_id_alter_contact_phone_and_more'),
        ('developers', '0006_developer_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='director',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contact', verbose_name='Руководитель предприятия'),
        ),
    ]
