# Generated by Django 4.1.3 on 2022-12-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0011_remove_developer_director_id_developer_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='contact_id',
        ),
    ]
