# Generated by Django 4.1.3 on 2022-12-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_listing_remove_contact_listing_id_and_more'),
        ('developers', '0012_remove_developer_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='director',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Руководитель', to='contacts.contact'),
        ),
    ]
