# Generated by Django 4.1.3 on 2022-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0013_developer_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='city_main_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город расположения головного офиса'),
        ),
    ]
